"""
scout_backend/settings.py

Project configuration for Scout's Django backend. This is the shell, not
a feature — it wires together:

  - environment-based secrets (.env, never committed — see .env.example)
  - installed apps (DRF + Scout's five feature apps + core)
  - the Supabase-hosted PostgreSQL connection
  - security settings appropriate for a platform handling personal documents

Scout's tables are hand-written in database/schema.sql, NOT generated by
Django migrations. Only Django's own internal tables (auth, sessions,
admin, authtoken) are migrated by Django. Every model that maps to a
schema.sql table must set `managed = False` (Rule 25).
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Environment variables (.env is never committed)
# ---------------------------------------------------------------------------
load_dotenv(BASE_DIR / ".env")


def env(key: str, default=None, required=False):
    value = os.environ.get(key, default)
    if required and value is None:
        raise RuntimeError(
            f"Missing required environment variable: {key}. "
            f"Check your .env against .env.example."
        )
    return value


def env_bool(key: str, default=False) -> bool:
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def env_list(key: str, default=None) -> list[str]:
    value = os.environ.get(key)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


SECRET_KEY = env("DJANGO_SECRET_KEY", required=True)
DEBUG = env_bool("DEBUG", default=False)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # Scout apps
    "core",
    "students",
    "opportunities",
    "applications",
    "notifications",
    "documents",
    "providers_admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "scout_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "scout_backend.wsgi.application"

# ---------------------------------------------------------------------------
# Database — Supabase-hosted PostgreSQL
#
# CONN_MAX_AGE is kept at 0 (no persistent connections) by default because
# Supabase's pooled connection string (pgbouncer, transaction mode) does
# not play well with Django holding connections open. If you switch to
# Supabase's direct connection (port 5432, not the 6543 pooler), you can
# raise this safely.
# ---------------------------------------------------------------------------

#supabase settings for the documents storage bucket
SUPABASE_URL = env("SUPABASE_URL", required=True)
SUPABASE_SERVICE_KEY = env("SUPABASE_SERVICE_KEY", required=True)
SUPABASE_BUCKET =env("SUPABASE_BUCKET", default="documents")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME", required=True),
        "USER": env("DB_USER", required=True),
        "PASSWORD": env("DB_PASSWORD", required=True),
        "HOST": env("DB_HOST", required=True),
        "PORT": env("DB_PORT", default="5432"),
        "CONN_MAX_AGE": int(env("DB_CONN_MAX_AGE", default="0")),
        "OPTIONS": {
            "sslmode": env("DB_SSLMODE", default="require"),
        },
    }
}

# ---------------------------------------------------------------------------
# Password validation (only relevant to Django's own auth_user table)
# ---------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 10}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Conservative MVP defaults (Rule 15). Tighten further per-view
        # (login, register, password reset) once those views exist —
        # these global rates are a floor, not a substitute.
        "anon": "20/min",
        "user": "120/min",
    },
}

# ---------------------------------------------------------------------------
# CORS — only the React dev server (and later, the deployed frontend) may
# call this API from a browser.
# ---------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:5173"],
)
CORS_ALLOW_CREDENTIALS = True

# ---------------------------------------------------------------------------
# Security — Scout handles personal documents; NFRs require encryption in
# transit and no sensitive data leaking through headers/cookies (Rule 19).
# ---------------------------------------------------------------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# HTTPS-only cookies/redirects — on by default whenever DEBUG is off, but
# still env-driven so local HTTP development isn't broken.
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)

# DRF auth tokens don't expire on their own. Session cookie expiration:
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------
LANGUAGE_CODE = "en-za"
TIME_ZONE = "Africa/Johannesburg"
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Logging — never log tokens, passwords, or document contents (Rule 31).
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.db.backends": {
            # Useful for spotting N+1 queries in dev, but query params can
            # be sensitive — leave at WARNING unless actively debugging.
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
