"""
WSGI config for scout_backend project.

Auto-generated by `django-admin startproject`, standard boilerplate — tells
a production WSGI server (e.g. gunicorn, used on Railway/Render) how to run
this app. You shouldn't need to edit this file; see settings.py for actual
configuration.
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "scout_backend.settings")

application = get_wsgi_application()